language: python
python:
 - "3.5.2"

install: 
 - pip install -r requirements.txt
 - pip install coveralls

addons:
  -postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE fast_food_db;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC to postgres;' -U postgres


script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls
 